--ÞEHÝRLERE GÖRE VERÝLEN SÝPARÝÞLERÝ TOPLAM OLARAK LÝSTELEME
--JOIN ve AGGREGATE FUNCTIONS KULLANIYORUZ

SELECT 
C.CITY SEHIR,
SUM (OD.LINETOTAL) TOPLAMFATURATUTARI,
SUM ( OD.AMOUNT) TOPLAMSIPARIS_ADEDI,
COUNT (OD.ID) TOPLAMSIPARIS_SAYISI

FROM 
ORDERS O
JOIN USERS U ON O.USERID = U.ID
JOIN ADDRESS A ON O.ID = A.USERID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID
JOIN INVOICES I ON I.ORDERID = O.ID
JOIN PAYMENTS P ON P.ORDERID = O.ID
JOIN INVOICEDETAILS IND ON IND.INVOICEID = I.ID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

--WHERE 
--O.ID = 26121 
--U.NAMESURNAME = 'CEYDA GEZGÝNCÝ'

GROUP BY C.CITY 
ORDER BY 2 DESC --SUM(OD.LINETOTAL) DESC
