--ÝL BAZINDA MÜÞTERÝ BAZLI TESLÝMAT SÜRESÝ GECÝKME ANALÝZÝ

SELECT
CT.CITY,
--U.ID KULL_ID, 
--U.NAMESURNAME MÜÞT_ADSOYAD,
--AVG (DATEDIFF (DAY, O.DATE_,I.DATE_)) TESLIMAT_SURESI,
AVG (DATEDIFF (HOUR, O.DATE_,I.DATE_)) ORT_TT_SAAT,
MAX (DATEDIFF (HOUR, O.DATE_,I.DATE_)) EN_UZUNTESLIMATSAATI,
MIN (DATEDIFF (HOUR, O.DATE_,I.DATE_)) EN_KISATESLIMATSAATI,
SUM ( O.TOTALPRICE ) TOPLAM_SIP_TUT,
COUNT ( O.ID ) SIPARIS_SAYISI

FROM ORDERS O
	JOIN USERS U ON U.ID=O.USERID
	JOIN ADDRESS A ON A.USERID =U.ID
	--JOIN COUNTRIES C ON C.ID = A.CITYID
	JOIN CITIES CT ON CT.ID=A.CITYID
	JOIN DISTRICTS D ON D.ID= A.DISTRICTID
	JOIN TOWNS T ON T.ID=A.TOWNID
	JOIN PAYMENTS P ON P.ORDERID = O.ID
	JOIN INVOICES I ON I.ORDERID=O.ID
	--JOIN INVOICEDETAILS INV ON INV.INVOICEID=I.ID
	--JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	--JOIN ITEMS ITM ON OD.ITEMID = ITM.ID

GROUP BY 
CT.CITY
ORDER BY 2 DESC