
--ÞEHÝRLERDE ADRES SAYISI
SELECT 
CT.CITY,
COUNT(U.NAMESURNAME) KULLANICISAYISI

FROM 
USERS U,
ADDRESS A,
COUNTRIES C,
CITIES CT,
TOWNS T,
DISTRICTS D

WHERE U.ID=A.USERID
AND C.ID = A.COUNTRYID
AND CT.ID = A.CITYID
AND T.ID = A.TOWNID
AND D.ID = A.DISTRICTID

GROUP BY CT.CITY