SELECT
DISTINCT O.ID SIPARIS_ID,
O.DATE_ SIPARIS_TARIHI,
I.DATE_ FATURA_TARIHI,
DATEDIFF (DAY, O.DATE_,I.DATE_) TESLIMAT_SURESI,
DATEDIFF (HOUR, O.DATE_,I.DATE_) TESLIMAT_SURESI_SAAT


FROM ORDERS O
	JOIN USERS U ON U.ID=O.USERID
	JOIN ADDRESS A ON A.USERID =U.ID
	--JOIN COUNTRIES C ON C.ID = A.CITYID
	JOIN CITIES CT ON CT.ID=A.CITYID
	JOIN DISTRICTS D ON D.ID= A.DISTRICTID
	JOIN TOWNS T ON T.ID=A.TOWNID
	JOIN PAYMENTS P ON P.ORDERID = O.ID
	JOIN INVOICES I ON I.ORDERID=O.ID
	--JOIN INVOICEDETAILS INV ON INV.INVOICEID=I.ID
	--JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	--JOIN ITEMS ITM ON OD.ITEMID = ITM.ID

