--ÖDEME TÜRÜNE GÖRE DAÐILIM

SELECT 
DATEPART ( MONTH, DATE_) AY,
DATEPART ( YEAR, DATE_) YIL,
SUM (PAYMENTTOTAL) TUTAR,

CASE 
	WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALE'
END AS ODEMETURU_ACIKLAMA

FROM PAYMENTS 

GROUP BY PAYMENTTYPE, DATEPART ( MONTH, DATE_), DATEPART ( YEAR, DATE_) 
ORDER BY DATEPART ( YEAR, DATE_) ,DATEPART ( MONTH, DATE_) 