SELECT 
U.USERNAME_ KULLANICIADI,
U.NAMESURNAME ADSOYAD,
C.CITY SEHIR,
T.TOWN KASABA,
D.DISTRICT MINTIKA,
A.ADDRESSTEXT ADRESSATIRI,
O.ID SIPARISNO,
O.DATE_ SIPARIS_TARIHI,
I.TOTALPRICE FATURATUTARI, 
P.DATE_ ODEMETARIHI,
P.APPROVECODE BANKAONAYKODU,
I.DATE_ FATURATARIHI,
I.CARGOFICHENO KARGOFISNO,
ITM.ITEMCODE URUNKODU, ITM.ITEMNAME URUNADI,
OD.AMOUNT MIKTAR, OD.UNITPRICE BIRIMFIYAT, OD.LINETOTAL SATIRTOPLAMI

FROM 
ORDERS O
JOIN USERS U ON O.USERID = U.ID
JOIN ADDRESS A ON O.ID = A.USERID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID
JOIN INVOICES I ON I.ORDERID = O.ID
JOIN PAYMENTS P ON P.ORDERID = O.ID
JOIN INVOICEDETAILS IND ON IND.INVOICEID = I.ID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

WHERE 
--O.ID = 26121 
U.NAMESURNAME = 'CEYDA GEZGÝNCÝ'
