SELECT 
U.NAMESURNAME ADSOYAD,
COUNT(A.ID) ADRESSAYISI,
COUNT(DISTINCT C.COUNTRY) ULKESAYISI,
COUNT (DISTINCT CT.ID) SEHIRSAYISI

FROM 
USERS U,
ADDRESS A,
COUNTRIES C,
CITIES CT,
TOWNS T,
DISTRICTS D

WHERE U.ID=A.USERID
AND C.ID = A.COUNTRYID
AND CT.ID = A.CITYID
AND T.ID = A.TOWNID
AND D.ID = A.DISTRICTID
--AND CT.CITY LIKE 'ÝZMÝR'

GROUP BY U.NAMESURNAME
HAVING COUNT (A.ID) > 2