--YILLARA VE AYLARA GÖRE SÝPARÝÞ DAÐILIMI

SELECT 
	DATEPART(YEAR,O.DATE_) YIL, 
	DATEPART (MONTH, O.DATE_) AY ,
	CASE 
		WHEN DATEPART (MONTH, O.DATE_)  = 1 THEN 'OCAK'
		WHEN DATEPART (MONTH, O.DATE_)  = 2 THEN 'ÞUBAT'
		WHEN DATEPART (MONTH, O.DATE_)  = 3 THEN 'MART'
		WHEN DATEPART (MONTH, O.DATE_)  = 4 THEN 'NÝSAN'
		WHEN DATEPART (MONTH, O.DATE_)  = 5 THEN 'MAYIS'
		WHEN DATEPART (MONTH, O.DATE_)  = 6 THEN 'HAZÝRAN'
		WHEN DATEPART (MONTH, O.DATE_)  = 7 THEN 'TEMMUZ' 
		WHEN DATEPART (MONTH, O.DATE_)  = 8 THEN  'AÐUSTOS'
		WHEN DATEPART (MONTH, O.DATE_)  = 9 THEN 'EYLÜL'
		WHEN DATEPART (MONTH, O.DATE_)  = 10 THEN 'EKÝM'
		WHEN DATEPART (MONTH, O.DATE_)  = 11 THEN 'KASIM'
		WHEN DATEPART (MONTH, O.DATE_)  = 12 THEN 'ARALIK'
	END AS AY_ADI,

	SUM (OD.LINETOTAL) TOPLAMSIPARIS_TUTAR,
	SUM (OD.AMOUNT) TOPLAMSIPARISMIKTAR,
	COUNT (OD.ID) TOPLAMSIPARIS_SAYISI

FROM 
	ORDERS O
	JOIN USERS U ON O.USERID = U.ID
	JOIN ADDRESS A ON O.ID = A.USERID
	JOIN CITIES C ON C.ID = A.CITYID
	JOIN TOWNS T ON T.ID = A.TOWNID
	JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	JOIN INVOICES I ON I.ORDERID = O.ID
	JOIN PAYMENTS P ON P.ORDERID = O.ID
	JOIN INVOICEDETAILS IND ON IND.INVOICEID = I.ID
	JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	JOIN ITEMS ITM ON ITM.ID = OD.ITEMID


GROUP BY DATEPART (MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)
ORDER BY DATEPART (MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)
