SELECT
U.NAMESURNAME,
C.COUNTRY,
CT.CITY,
T.TOWN,
D.DISTRICT

FROM
USERS U

JOIN ADDRESS A ON A.USERID = U.ID
JOIN COUNTRIES C ON A.COUNTRYID = C.ID
JOIN CITIES CT ON A.CITYID = CT.ID
JOIN TOWNS T ON A.TOWNID = T.ID
JOIN DISTRICTS D ON A.DISTRICTID = D.ID

ORDER BY NAMESURNAME