SELECT
U.NAMESURNAME ADSOYAD,
U.EMAIL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMGUNU,
A.ADDRESSTEXT ACIKADRES,
C.COUNTRY ULKEADI,
CT.CITY SEHIR,
T.TOWN ILCE,
D.DISTRICT MAHALLE,
A.POSTALCODE POSTAKODU

FROM 
USERS U,
ADDRESS A,
COUNTRIES C,
CITIES CT, 
TOWNS T,
DISTRICTS D

WHERE U.ID=A.USERID 
AND C.ID=A.COUNTRYID
AND CT.ID=A.CITYID
AND T.ID=A.TOWNID
AND D.ID=A.DISTRICTID
AND U.ID=1
