--TARÝHE GÖRE SÝPARÝÞ DAÐILIMI (ÝLK 10)

SELECT 
TOP 10
CONVERT ( DATE,O.DATE_) TARIH,
SUM (OD.LINETOTAL) TOPLAMSIPARIS_TUTAR,
SUM (OD.AMOUNT) TOPLAMSIPARISMIKTAR,
SUM (OD.ID) TOPLAMSIPARIS_SAYISI

FROM 
ORDERS O
JOIN USERS U ON O.USERID = U.ID
JOIN ADDRESS A ON O.ID = A.USERID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID
JOIN INVOICES I ON I.ORDERID = O.ID
JOIN PAYMENTS P ON P.ORDERID = O.ID
JOIN INVOICEDETAILS IND ON IND.INVOICEID = I.ID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY 
CONVERT ( DATE,O.DATE_)