--ÜRÜN KATEGORÝLERÝNE GÖRE SÝPARÝÞ DAÐILIMI

SELECT 
ITM.CATEGORY1 KATEGORI1,
ITM.CATEGORY2,
ITM.CATEGORY3,
ITM.CATEGORY4,
SUM (OD.LINETOTAL) TOPLAMFATURATUTARI,
SUM ( OD.AMOUNT) TOPLAMSIPARIS_ADEDI,
COUNT (OD.ID) TOPLAMSIPARIS_SAYISI,
SUM (OD.LINETOTAL) / SUM (OD.AMOUNT) ORTALAMA_BIRIMFIYAT

FROM 
ORDERS O
JOIN USERS U ON O.USERID = U.ID
JOIN ADDRESS A ON O.ID = A.USERID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID
JOIN INVOICES I ON I.ORDERID = O.ID
JOIN PAYMENTS P ON P.ORDERID = O.ID
JOIN INVOICEDETAILS IND ON IND.INVOICEID = I.ID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

--WHERE ITM.CATEGORY1 = 'KOZMETIK'
GROUP BY CATEGORY1, CATEGORY2, CATEGORY3,CATEGORY4
ORDER BY 1