--HANGÝ ÞEHÝRDE KAÇ KULLANICI VAR
SELECT
CT.CITY SEHIR,
COUNT (U.ID) KULLANICISAYISI

FROM
USERS U

JOIN ADDRESS A ON A.USERID = U.ID
JOIN COUNTRIES C ON A.COUNTRYID = C.ID
JOIN CITIES CT ON A.CITYID = CT.ID
JOIN TOWNS T ON A.TOWNID = T.ID
JOIN DISTRICTS D ON A.DISTRICTID = D.ID

GROUP BY CT.CITY
ORDER BY CT.CITY