SELECT 
U.USERNAME_ KULLANICIADI,
U.NAMESURNAME ADSOYAD,
C.CITY SEHIR,
T.TOWN KASABA,
D.DISTRICT MINTIKA,
A.ADDRESSTEXT ADRESSATIRI,
O.ID SIPARISNO,
O.DATE_ SIPARIS_TARIHI,
I.TOTALPRICE FATURATUTARI, 
P.DATE_ ODEMETARIHI,
P.APPROVECODE BANKAONAYKODU,
I.DATE_ FATURATARIHI,
I.CARGOFICHENO KARGOFISNO

FROM 
USERS U
JOIN ADDRESS A ON U.ID = A.USERID
JOIN CITIES C ON C.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
JOIN DISTRICTS D ON D.ID = A.DISTRICTID
JOIN ORDERS O ON O.USERID = U.ID
JOIN INVOICES I ON I.ORDERID = O.ID
-- JOIN INVOICEDETAILS IND ON IND.INVOICEID = I.ID
JOIN PAYMENTS P ON P.ORDERID = O.ID

WHERE U.NAMESURNAME LIKE  ('CEYDA GEZGÝNCÝ')